name: Test suite
on:
  push:
    branches:
      - master
  pull_request:
env:
  # Deny warnings in CI
  RUSTFLAGS: "-D warnings"
jobs:
  cargo-fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Check formatting with cargo fmt
      run: cargo fmt --all -- --check
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Run tests
      run: cargo test --release --all-features
